env:
  TERM: xterm-256color

window:
  padding:
    x: 0
    y: 0

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000

font:
  normal:
    family: "MesloLGS NF" # should be "Menlo" or something on macOS.
    style: Regular

  bold:
    family: "MesloLGS NF"
    style: Bold

  italic:
    family: "MesloLGS NF"
    style: Italic

  size: 10

  offset:
    x: 1
    y: 10

  #glyph_offset:
    x: 0
    y: 0

# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  normal:
    black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#caa9fa'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bfbfbf'

  bright:
    black:   '#575b70'
    red:     '#ff6e67'
    green:   '#5af78e'
    yellow:  '#f4f99d'
    blue:    '#caa9fa'
    magenta: '#ff92d0'
    cyan:    '#9aedfe'
    white:   '#e6e6e6'

background_opacity: 0.98

unfocused_hollow: true
